name: Docker Image Latest

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io


jobs:

  build-and-publish-latest:
    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/main'  # Running this job only for main branch

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: lowercase github.repository
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
#            docker.io/${{ github.repository }}
          images: |
            ghcr.io/${{ github.repository }}
#          images: |
#            ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          DOCKER_BUILDKIT: 1
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

#      - name: Build and push Docker image Latest
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          push: true
#          tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
