# https://github.com/marketplace/actions/publish-python-poetry-package
name: PyPi Package
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.17
        with:
          python_version: "3.12"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
